# frozen_string_literal: true

source "https://rubygems.org"

gem "rake", "~> 13.4"
gem "redis-client", "~> 0.30"
gem "yard", "~> 0.9.44"

source "https://rubygems.pkg.github.com/kanutocd" do
  gem "cdc-orchestrator-pro", "0.9.0"
  gem "cdc-redis-pro", "0.9.0"
end
