source "https://rubygems.org"

source "https://rubygems.pkg.github.com/kanutocd" do
  gem "cdc-orchestrator-pro", "~> 0.9.0"
  gem "cdc-redis-pro", "~> 0.9.0"
end

gem "rails", "~> 8.1.3"
gem "propshaft"
gem "sqlite3", ">= 2.1"
gem "puma", ">= 5.0"
gem "bootsnap", require: false

gem "tzinfo-data", platforms: %i[ windows jruby ]

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "bundler-audit", require: false
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
end

group :development do
  gem "web-console"
  gem "yard", require: false
end
